### ISSUE TITLE
Please add documentation regarding stateless nature of the container

### ISSUE THREAD

**Issue by blueelvis** [Azure-App-Service/nginx-fpm#3]
Hi,

Could you please add some documentation to this repository stating that it is strongly suggested to add `WEBSITES_ENABLE_APP_SERVICE_STORAGE = true` to the application settings because otherwise, any changes made with Drush to a drupal installation will not persist if the web app is rebooted.

Thanks!

**Comment by fanjeffrey** [comment]
We've documented this in README.md. Thank you for the comment.

**Comment by blueelvis** [comment]
Perfect!
